/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LichCongTacRouteImport } from './routes/lich-cong-tac'
import { Route as GioiThieuRouteImport } from './routes/gioi-thieu'
import { Route as DuKhachRouteImport } from './routes/du-khach'
import { Route as DoanhNghiepRouteImport } from './routes/doanh-nghiep'
import { Route as CongDanRouteImport } from './routes/cong-dan'
import { Route as ChinhQuyenRouteImport } from './routes/chinh-quyen'
import { Route as IndexRouteImport } from './routes/index'

const LichCongTacRoute = LichCongTacRouteImport.update({
  id: '/lich-cong-tac',
  path: '/lich-cong-tac',
  getParentRoute: () => rootRouteImport,
} as any)
const GioiThieuRoute = GioiThieuRouteImport.update({
  id: '/gioi-thieu',
  path: '/gioi-thieu',
  getParentRoute: () => rootRouteImport,
} as any)
const DuKhachRoute = DuKhachRouteImport.update({
  id: '/du-khach',
  path: '/du-khach',
  getParentRoute: () => rootRouteImport,
} as any)
const DoanhNghiepRoute = DoanhNghiepRouteImport.update({
  id: '/doanh-nghiep',
  path: '/doanh-nghiep',
  getParentRoute: () => rootRouteImport,
} as any)
const CongDanRoute = CongDanRouteImport.update({
  id: '/cong-dan',
  path: '/cong-dan',
  getParentRoute: () => rootRouteImport,
} as any)
const ChinhQuyenRoute = ChinhQuyenRouteImport.update({
  id: '/chinh-quyen',
  path: '/chinh-quyen',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chinh-quyen': typeof ChinhQuyenRoute
  '/cong-dan': typeof CongDanRoute
  '/doanh-nghiep': typeof DoanhNghiepRoute
  '/du-khach': typeof DuKhachRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lich-cong-tac': typeof LichCongTacRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chinh-quyen': typeof ChinhQuyenRoute
  '/cong-dan': typeof CongDanRoute
  '/doanh-nghiep': typeof DoanhNghiepRoute
  '/du-khach': typeof DuKhachRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lich-cong-tac': typeof LichCongTacRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chinh-quyen': typeof ChinhQuyenRoute
  '/cong-dan': typeof CongDanRoute
  '/doanh-nghiep': typeof DoanhNghiepRoute
  '/du-khach': typeof DuKhachRoute
  '/gioi-thieu': typeof GioiThieuRoute
  '/lich-cong-tac': typeof LichCongTacRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chinh-quyen'
    | '/cong-dan'
    | '/doanh-nghiep'
    | '/du-khach'
    | '/gioi-thieu'
    | '/lich-cong-tac'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chinh-quyen'
    | '/cong-dan'
    | '/doanh-nghiep'
    | '/du-khach'
    | '/gioi-thieu'
    | '/lich-cong-tac'
  id:
    | '__root__'
    | '/'
    | '/chinh-quyen'
    | '/cong-dan'
    | '/doanh-nghiep'
    | '/du-khach'
    | '/gioi-thieu'
    | '/lich-cong-tac'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChinhQuyenRoute: typeof ChinhQuyenRoute
  CongDanRoute: typeof CongDanRoute
  DoanhNghiepRoute: typeof DoanhNghiepRoute
  DuKhachRoute: typeof DuKhachRoute
  GioiThieuRoute: typeof GioiThieuRoute
  LichCongTacRoute: typeof LichCongTacRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lich-cong-tac': {
      id: '/lich-cong-tac'
      path: '/lich-cong-tac'
      fullPath: '/lich-cong-tac'
      preLoaderRoute: typeof LichCongTacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gioi-thieu': {
      id: '/gioi-thieu'
      path: '/gioi-thieu'
      fullPath: '/gioi-thieu'
      preLoaderRoute: typeof GioiThieuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/du-khach': {
      id: '/du-khach'
      path: '/du-khach'
      fullPath: '/du-khach'
      preLoaderRoute: typeof DuKhachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doanh-nghiep': {
      id: '/doanh-nghiep'
      path: '/doanh-nghiep'
      fullPath: '/doanh-nghiep'
      preLoaderRoute: typeof DoanhNghiepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cong-dan': {
      id: '/cong-dan'
      path: '/cong-dan'
      fullPath: '/cong-dan'
      preLoaderRoute: typeof CongDanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chinh-quyen': {
      id: '/chinh-quyen'
      path: '/chinh-quyen'
      fullPath: '/chinh-quyen'
      preLoaderRoute: typeof ChinhQuyenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChinhQuyenRoute: ChinhQuyenRoute,
  CongDanRoute: CongDanRoute,
  DoanhNghiepRoute: DoanhNghiepRoute,
  DuKhachRoute: DuKhachRoute,
  GioiThieuRoute: GioiThieuRoute,
  LichCongTacRoute: LichCongTacRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
